### ISSUE TITLE
Proposal to Modify Repository to Address Non-Annotated Attributes in Pydantic

### ISSUE THREAD

**Issue by ini-ei** [jiangjiechen/auction-arena#2]
Hello,

I have encountered an issue with non-annotated attributes when using Pydantic in our project. Specifically, attributes like openai_cost = 0 are causing a PydanticUserError because they lack type annotations and are incorrectly treated as model fields.

**Detailed Error**
`pydantic.errors.PydanticUserError: A non-annotated attribute was detected: openai_cost = 0 All model fields require a type annotation; if openai_cost is not meant to be a field, you may be able to resolve this error by annotating it as a ClassVar or updating model_config['ignored_types']
`
**Proposed Solution**
1.Annotate openai_cost as a ClassVar[int] to clarify that it is not a field of the Pydantic model.
1.Update the model_config['ignored_types'] to exclude certain types from being treated as model fields.

**Comment by jiangjiechen** [comment]
Thanks for the suggestion! I'll fix it shortly.
